name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Rust project
        run: cargo build --verbose

      - name: Run tests (if any)
        run: cargo test --verbose || echo "No tests yet"
